### PR TITLE
Refactored foreach to map

### PR DESCRIPTION
**Pull request by arzola**
Fancy collection function seems nicer

### CODE REVIEW

**Comment by vojtasvoboda** [comment]
Thanks! Looks good to me, but - can you please change the indentation from 2 spaces to 4 spaces? Just to be consistent. Thanks in advance

**Comment by arzola** [comment]
Sure no problem

**Comment by vojtasvoboda** [comment]
Great! Thank you!

If you want a have some time, I would also appreciate making some new translate file for your native language https://github.com/vojtasvoboda/oc-userbanned-plugin/tree/master/lang 👍

**Review by vojtasvoboda — COMMENTED** [review]
👍

**Pull request merged**
